//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUY_PRODUCTS
    {
        public int ID_BUY { get; set; }
        public int ID_PRODUCT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public int QUANTITY { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual BUYS BUYS { get; set; }
        public virtual Product Product { get; set; }
    }
}
