//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUYS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUYS()
        {
            this.BUY_PRODUCTS = new HashSet<BUY_PRODUCTS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_CLIENT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUY_PRODUCTS> BUY_PRODUCTS { get; set; }
        public virtual CLIENT CLIENT { get; set; }
    }
}
