//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public Nullable<System.DateTime> FROM { get; set; }
        public Nullable<System.DateTime> TO { get; set; }
        public Nullable<double> PERCENTAGE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
